# Generated by Django 4.1.3 on 2023-08-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('is_teacher', models.BooleanField(default=False)),
                ('instrument', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pronouns', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('guardian_names', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('profile_image_url', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiostarapi.user')),
            ],
        ),
    ]
