# Generated by Django 4.1.3 on 2023-08-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studiostarapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sticker_goal', models.IntegerField()),
                ('current_stickers', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiostarapi.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiostarapi.sticker')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiostarapi.task')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='studiostarapi.user')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relationships', to='studiostarapi.user')),
            ],
            options={
                'unique_together': {('teacher_id', 'student_id')},
            },
        ),
    ]
