# Generated by Django 4.1.3 on 2023-08-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studiostarapi', '0002_sticker_task_tasksticker_teacherstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_names',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
