# Generated by Django 4.2.1 on 2023-08-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studiostarapi', '0003_alter_user_birthdate_alter_user_guardian_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiostarapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudioStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiostarapi.user')),
                ('studio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiostarapi.studio')),
            ],
        ),
    ]
